import panel
import xarray as xr


def plot_one_var_cdf(cdf_da: xr.Dataset, var: str) -> panel.layout.base.Column:
    """Plot CDF for a single variable.

    Written to function for the unique configuration of the CDF DataArray object
    generated by the climakitae TMY class.
    Silences an annoying hvplot warning
    Will show every simulation together on the plot

    Parameters
    -----------
    cdf: xr.DataArray
       Cumulative density function for a single variable

    Returns
    -------
    panel.layout.base.Column
        Hvplot lineplot

    """
    cdf_da = cdf_da[var]
    prob_da = cdf_da.sel(data="probability", drop=True).rename(
        "probability"
    )  # Grab only probability da
    bins_da = cdf_da.sel(data="bins", drop=True).rename("bins")  # Grab just bin values
    ds = xr.merge([prob_da, bins_da])  # Merge the two to form a single Dataset object
    cdf_pl = ds.hvplot(
        "bins",
        "probability",
        by="simulation",  # Simulations should all be displayed together
        widget_location="bottom",
        grid=True,
        xlabel="{0} ({1})".format(var, cdf_da.attrs["units"]),
        xlim=(
            bins_da.min().item(),
            bins_da.max().item(),
        ),  # Fix the x-limits for all months
        ylabel="Probability (0-1)",
    )
    return cdf_pl
